name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      ANDROIDAPI: 31
      ANDROIDMINAPI: 21

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-venv git zip unzip openjdk-8-jdk \
            build-essential autoconf automake libtool pkg-config zlib1g-dev \
            libjpeg-dev libfreetype6-dev libssl-dev

      - name: Create & activate venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install Buildozer & requirements
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython appdirs packaging
          pip install -r requirements.txt

      - name: Build APK
        run: |
          source .venv/bin/activate
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: pontoeletronico-apk
          path: ./.buildozer/bin/*.apk

